#define ERROR_NONE  0
#define ERROR_INVALID_PACKET 3002
#define ERROR_AUTHORIZE_FAILED 3003
#define ERROR_MSGSRV_ERROR 3004
// socke open
#define ERROR_SOCKET_CREATE_ERROR 3101
#define ERROR_SOCKET_CONNECT_ERROR 3102
#define ERROR_SOCKET_UNKOWN_ERROR 3103
// socket read
#define ERROR_SOCKET_READ_ERROR 3111
#define ERROR_SOCKET_READ_TIMEOUT 3112
#define ERROR_SOCKET_WRITE_ERROR 3113
// extension error
#define ERROR_APPLICATION_NOT_FOUND  3404
#define ERROR_INTERNAL_EXCEPTION 3501

// Recevie callback status
#define STATUS_OK 1
#define STATUS_NO_AVAILABLE 0
#define STATUS_CLOSED -1
#define STATUS_TIMEOUT -2
#define STATUS_READ_ERROR -3
#define STATUS_INTERNAL_ERROR -4
#define STATUS_TARGET_NOT_FOUND -5
#define STATUS_MSGSRV_ERROR -6

// default
#define DEFAULT_DEBUG_LEVEL 0
#define DEFAULT_READ_BUFFER_SIZE 1024
#define DEFAULT_REQUEST_TIMEOUT 30000
#define DEFAULT_READ_TIMEOUT 16000
#define DEFAULT_SELECT_TIMEOUT 1000

// msgsrv_functions.c
#define MSGSRV_DELIMITER " "
#define LOCAL_MSGSRV_APPNAME "."
#define MSGSRV_MSG_LIMIT 3
#define MSGSRV_CONTENT_LIMIT 8
#define MSGSRV_KEY_APPNAME "appname"
#define MSGSRV_KEY_COMMAND "command"
#define MSGSRV_KEY_CONTENT "content"

// msgsrv commands
#define MSGSRV_CMD_HELLO "HELO"
#define MSGSRV_CMD_APPNAME "AppName"
#define MSGSRV_CMD_AUTH "AUTH"
#define MSGSRV_CMD_USER "User"
#define MSGSRV_CMD_ACCESS "ACCESS"
#define MSGSRV_CMD_ERROR "ERROR"

#define MSGSRV_ACCESS_GRANTED "GRANTED"
#define MSGSRV_ACCESS_DENY "DENY"
#define MSGSRV_ERROR_APPLICATION "APPLICATION"

// unix_socket.c / win32_socket.c
#define SOCKET_SELECT_ERROR -3
#define SOCKET_READ_ERROR -4
#define SOCKET_READ_TIMEOUT -8
#define SOCKET_WRITE_ERROR -5
#define SOCKET_WRITE_NULL -6
#define SOCKET_BEYONE_LIMIT -7
#define SOCKET_INVALID -1
#define SOCKET_NO_DATA 0
#define ALLOCATE_FAILED -2

#define TRUE 1
#define FALSE 0

#define PHP_MSGSRV_DESCRIPTOR_RES_NAME "msgsrv link"
